# Ubuntu  with Java 8 installed.
# Build image with:  docker build  -f Dockerfile_Java8  --rm=true -t=java8
# Run with: docker run -it java8
FROM ubuntu

MAINTAINER Mike
# Using && prevents intermediate containers being generated
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean
  
RUN apt-get install -y git &&  apt-get install -y maven
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
# Default command
CMD ["bash"]
